// Navigation
export const SET_FOOTER_TAB = 'SET_FOOTER_TAB';
export const SELECT_CHAPTER = 'SELECT_CHAPTER';

// Initialize Database
export const INITIALIZE_FIREBASE_REQUEST = 'INITIALIZE_FIREBASE_REQUEST';
export const INITIALIZE_FIREBASE_SUCCESS = 'INITIALIZE_FIREBASE_SUCCESS';
export const BUILD_REALM_SCHEMA = 'BUILD_REALM_SCHEMA';
export const DOWNLOAD_IDS_REQUEST = 'DOWNLOAD_IDS_REQUEST';
export const DOWNLOAD_IDS_FAILURE = 'DOWNLOAD_IDS_FAILURE';
export const DOWNLOAD_IDS_SUCCESS = 'DOWNLOAD_IDS_SUCCESS';

// PharmaCare
export const DOWNLOAD_PHARMACARE_REQUEST = 'DOWNLOAD_PHARMACARE_REQUEST';
export const DOWNLOAD_PHARMACARE_FAILURE = 'DOWNLOAD_PHARMACARE_FAILURE';
export const DOWNLOAD_PHARMACARE_SUCCESS = 'DOWNLOAD_PHARMACARE_SUCCESS';
export const GET_PHARMACARE_CHAPTERS = 'GET_PHARMACARE_CHAPTERS';
export const GET_PHARMACARE_CONTENT = 'GET_PHARMACARE_CONTENT';