export {default as Card} from './card/card';
export {default as Splash} from './splash/splash';
export {default as PreSplash} from './presplash/presplash';
export {default as FooterTabs} from './footertabs/footertabs';
export {default as Navbar} from './navbar/navbar';
export {default as Schedules} from './schedules/schedules';
export {default as Settings} from './settings/settings';
export {default as PharmaCareHome} from './pharmacare/pharmacarehome';
export {default as PharmaCareContent} from './pharmacare/pharmacarecontent';
